### PR TITLE
Fix case where Traefik can read empty plugin configuration file.

### PR DESCRIPTION
**Pull request by nokjuh**
Fixed a case where Traefik can read an empty or missing file when reading the Service Fabric configuration file generated by the plugin, with some unlucky timing. Traefik reads the configuration file every few seconds, and this can randomly lead to Traefik thinking that there are no Service Fabric resources to route to. This will lead to all requests to that Traefik instance failing for a few seconds until the next time Traefik reads the configuration.

Changed the configuration file to be written to a temporary file first, and only then replacing the configuration file that Traefik reads. This replacing should be an atomic operation, preventing Traefik from having a time when it can read an empty or missing configuration. I've tested that in practice the empty configuration file case no longer happens with this fix.

### CODE REVIEW

**Comment by nokjuh** [comment]
@microsoft-github-policy-service agree company="M-Files"

**Comment by tony-gamble-asos** [comment]
What is the behaviour when Traefik is configured to monitor a directory for its routers and services and a new temp file is momentarily created in the same directory?

**Comment by nokjuh** [comment]
At least I haven't found any issues, and our testing setup for our software extensively changes the Traefik routings while testing so we should have noticed any errors the same way we noticed them earlier. I'm not sure how to verify whether Traefik ever handles the temporary file at all.

Though there are now the following type of errors in the logs, often several per minute. Most likely from where the plugin is replacing the main configuration file with the temporary file. They don't seem to cause practical issues and I don't know how to avoid them.
time="2024-01-09T06:34:25Z" level=error msg="Error occurred during watcher callback: ..\\work\\sf_discovered.yaml: error reading configuration file: ..\\work\\sf_discovered.yaml - open ..\\work\\sf_discovered.yaml: The process cannot access the file because it is being used by another process." providerName=file

**Comment by egaribay77** [comment]
LGTM!

**Pull request merged**
