### PR TITLE
Add partition rules for stateful services only #5

### PR DESCRIPTION
**Pull request by Mahons**
@dario-ms  As per our previous [discussion](https://github.com/dariopb/traefikServiceFabricPlugin/issues/12) on this topic, we agreed that it made sense to only generate partitions for stateful services. Therefore, I have added a clause to ensure partition routes are only added if the service kind is stateful.

### CODE REVIEW

**Comment by Mahons** [comment]
@craftyhouse @dario-ms  it would be great if you got a chance to review this PR and merge it.

**Comment by Mahons** [comment]
@microsoft-github-policy-service agree [company="MTechSolutions Ltd"]

**Comment by Mahons** [comment]
@microsoft-github-policy-service agree

**Comment by egaribay77** [comment]
@Mahons Thanks for contributing will approve the PR.

**Pull request merged**
